# Site settings

url: "http://machineweb.github.io"
repo: "https://github.com/machineweb/machineweb.github.io"
title: "The Machine Live"
author: "The Machine Live, LLC"
description: "Pink Floyd Show"
keywords: "pink, floyd, pink floyd, Pink Floyd, The Machine, The Machine, the machine, machine live, Machine Live, light show, lightshow, rock, concert"
google-tracking-id: "0"

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  Tour: 'tour'
  News: 'news'
  About: 'about'
  Contact: 'contact'

background-img: "/img/intro-bg.jpg"

# About variables

me-img: "/img/me.jpg"

# Blog variables
paginate: 15

paginate_path: "blog/page:num"

post-preview-words: 128

disqus-shortname: "TheMachine"

fb-share: True
twitter-share: True
reddit-share: True

# Social networks variables (many more available: facebook, flickr, dribbble, pinterest, instagram, tumblr etc.)
social:
  - title: "facebook"
    url: "http://www.facebook.com/pages/The-Machine/56922104274"
  - title: "twitter"
    url: "https://twitter.com/themachinelive"
  - title: "instagram"
    url: "http://instagram.com/themachinelive"
  - title: "youtube"
    url: "https://youtube.com/channel/UCVp6Jz7PFKRqsxYpeAJCH0Q"

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]

gems:
  - jekyll-paginate
  - jemoji
